/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author michaelmartinez
 */
public class empleados extends javax.swing.JFrame {

    /**
     * Creates new form empleados
     */
    public empleados() {
        initComponents();
        conexion conex = new conexion();
        conex.getConexion();
        jTextId.setVisible(false);
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextTipoDocum = new javax.swing.JTextField();
        jTextNumDocum = new javax.swing.JTextField();
        jTextNombres = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jTextEstCivil = new javax.swing.JTextField();
        jTextGenero = new javax.swing.JTextField();
        jTextDirec = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextInfoAcade = new javax.swing.JTextArea();
        jButtonGuardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jTextFecha = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Funcionarios");

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID de empleado", "Tipo de documento", "Numero de documento", "Nombres", "Apellidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionarios);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel2.setText("Tipo de documento");

        jLabel3.setText("Numero de documento");

        jLabel4.setText("Nombres");

        jLabel5.setText("Apellidos");

        jLabel6.setText("Estado civil");

        jLabel7.setText("Genero");

        jLabel8.setText("Direccion");

        jLabel9.setText("Fecha de nacimiento");

        jLabel10.setText("Informacion academica");

        jTextInfoAcade.setColumns(20);
        jTextInfoAcade.setRows(5);
        jScrollPane2.setViewportView(jTextInfoAcade);

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextTipoDocum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDirec)
                            .addComponent(jTextEstCivil)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jTextNombres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jTextApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(jTextGenero)
                                .addComponent(jTextNumDocum)
                                .addComponent(jTextFecha))
                            .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificar)
                        .addContainerGap(115, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTipoDocum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNumDocum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEstCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonGuardar))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        String tipo_de_documento = jTextTipoDocum.getText();
        int numero_de_documento = Integer.parseInt(jTextNumDocum.getText());
        String nombres = jTextNombres.getText();
        String apellidos = jTextApellidos.getText();
        String estado_civil = jTextEstCivil.getText();
        String genero = jTextGenero.getText();
        String direccion = jTextDirec.getText();
        String fecha_de_nacimiento = jTextFecha.getText();
        String informacion_academica = jTextInfoAcade.getText();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.sql.Date fechaConvertida = null;

        try {
            java.util.Date parsed = dateFormat.parse(fecha_de_nacimiento);
            fechaConvertida = new java.sql.Date(parsed.getTime());
        } catch (Exception e) {
            System.out.println("Error occurred" + e.getMessage());
        }

        try {
            conexion objetoConexion = new conexion();

            PreparedStatement ps = objetoConexion.getConexion().prepareStatement("INSERT INTO funcionarios (tipo_de_documento, numero_de_documento, nombres, apellidos, estado_civil, genero, direccion, fecha_de_nacimiento, informacion_academica) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");

            ps.setString(1, tipo_de_documento);
            ps.setInt(2, numero_de_documento);
            ps.setString(3, nombres);
            ps.setString(4, apellidos);
            ps.setString(5, estado_civil);
            ps.setString(6, genero);
            ps.setString(7, direccion);
            ps.setDate(8, fechaConvertida);
            ps.setString(9, informacion_academica);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "datos guardados en funcionario");
            limpiar();
            cargarDatos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

        try {
            conexion objetoConexion = new conexion();

            PreparedStatement ps = objetoConexion.getConexion().prepareStatement("INSERT INTO genero (numero_de_documento, genero) VALUES (?, ?)");

            ps.setInt(1, numero_de_documento);
            ps.setString(2, genero);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "datos guardados en genero");
            limpiar();
            cargarDatos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }


    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionariosMouseClicked
        // TODO add your handling code here:

        try {
            int fila = jTableFuncionarios.getSelectedRow();
            int id = Integer.parseInt(jTableFuncionarios.getValueAt(fila, 0).toString());

            PreparedStatement ps;
            ResultSet rs;

            conexion objetoConexion = new conexion();
            ps = objetoConexion.getConexion().prepareStatement("SELECT tipo_de_documento, numero_de_documento, nombres, apellidos, estado_civil, genero, direccion, fecha_de_nacimiento, informacion_academica FROM funcionarios WHERE id_funcionario=? ");

            ps.setInt(1, id);
            rs = ps.executeQuery();

            while (rs.next()) {

                jTextId.setText(String.valueOf(id));
                jTextTipoDocum.setText(rs.getString("tipo_de_documento"));
                jTextNumDocum.setText(rs.getString("numero_de_documento"));
                if (!jTextNumDocum.getText().isEmpty()) {
                    jTextNumDocum.setEnabled(false);
                } else {
                    jTextNumDocum.setEnabled(true);
                }
                jTextNombres.setText(rs.getString("nombres"));
                jTextApellidos.setText(rs.getString("apellidos"));
                jTextEstCivil.setText(rs.getString("estado_civil"));
                jTextGenero.setText(rs.getString("genero"));
                jTextDirec.setText(rs.getString("direccion"));
                jTextFecha.setText(rs.getString("fecha_de_nacimiento"));
                jTextInfoAcade.setText(rs.getString("informacion_academica"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jTableFuncionariosMouseClicked

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        int id_funcionario = Integer.parseInt(jTextId.getText());
        String tipo_de_documento = jTextTipoDocum.getText();
        int numero_de_documento = Integer.parseInt(jTextNumDocum.getText());
        String nombres = jTextNombres.getText();
        String apellidos = jTextApellidos.getText();
        String estado_civil = jTextEstCivil.getText();
        String genero = jTextGenero.getText();
        String direccion = jTextDirec.getText();
        String fecha_de_nacimiento = jTextFecha.getText();
        String informacion_academica = jTextInfoAcade.getText();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.sql.Date fechaConvertida = null;

        try {
            java.util.Date parsed = dateFormat.parse(fecha_de_nacimiento);
            fechaConvertida = new java.sql.Date(parsed.getTime());
        } catch (Exception e) {
            System.out.println("Error occurred" + e.getMessage());
        }

        try {
            conexion objetoConexion = new conexion();

            PreparedStatement ps = objetoConexion.getConexion().prepareStatement("UPDATE funcionarios  SET tipo_de_documento=?, numero_de_documento=?, nombres=?, apellidos=?, estado_civil=?, genero=?, direccion=?, fecha_de_nacimiento=?, informacion_academica=? WHERE id_funcionario=? ");
            ps.setString(1, tipo_de_documento);
            ps.setInt(2, numero_de_documento);
            ps.setString(3, nombres);
            ps.setString(4, apellidos);
            ps.setString(5, estado_civil);
            ps.setString(6, genero);
            ps.setString(7, direccion);
            ps.setDate(8, fechaConvertida);
            ps.setString(9, informacion_academica);
            ps.setInt(10, id_funcionario);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "datos modificados en funcionario");
            limpiar();
            cargarDatos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

        try {
            conexion objetoConexion = new conexion();

            PreparedStatement ps = objetoConexion.getConexion().prepareStatement("UPDATE genero SET  numero_de_documento=?, genero=? WHERE numero_de_documento=? ");
            ps.setInt(1, numero_de_documento);
            ps.setString(2, genero);
            ps.setInt(3, numero_de_documento);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, ps.toString());
            limpiar();
            cargarDatos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:

        int numero_de_documento = Integer.parseInt(jTextNumDocum.getText());

        try {
            conexion objetoConexion = new conexion();

            PreparedStatement ps = objetoConexion.getConexion().prepareStatement("DELETE FROM genero WHERE numero_de_documento=? ");
            ps.setInt(1, numero_de_documento);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "datos eliminados");
            limpiar();
            cargarDatos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

        try {
            conexion objetoConexion = new conexion();

            PreparedStatement ps = objetoConexion.getConexion().prepareStatement("DELETE FROM funcionarios WHERE numero_de_documento=? ");
            ps.setInt(1, numero_de_documento);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "datos eliminados");
            limpiar();
            cargarDatos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }


    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:

        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void limpiar() {
        jTextId.setText("");
        jTextTipoDocum.setText("");
        jTextNumDocum.setText("");
        jTextNombres.setText("");
        jTextApellidos.setText("");
        jTextEstCivil.setText("");
        jTextGenero.setText("");
        jTextDirec.setText("");
        jTextFecha.setText("");
        jTextInfoAcade.setText("");
        if (!jTextNumDocum.getText().isEmpty()) {
            jTextNumDocum.setEnabled(false);
        } else {
            jTextNumDocum.setEnabled(true);
        }

    }

    private void cargarDatos() {

        DefaultTableModel modeloTabla = (DefaultTableModel) jTableFuncionarios.getModel();
        modeloTabla.setRowCount(0);

        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;

        try {

            conexion objetoConexion = new conexion();

            ps = objetoConexion.getConexion().prepareStatement("SELECT id_funcionario, tipo_de_documento, numero_de_documento, nombres, apellidos FROM funcionarios");

            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();

            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int indice = 0; indice < columnas; indice++) {
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextDirec;
    private javax.swing.JTextField jTextEstCivil;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextGenero;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextArea jTextInfoAcade;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextField jTextNumDocum;
    private javax.swing.JTextField jTextTipoDocum;
    // End of variables declaration//GEN-END:variables
}
